### ISSUE TITLE
CKFinder.modal does not allow to use more than one CKFinder on a page

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#10]
1. Use the following sample: https://gist.github.com/wwalc/101cd1fc7d37046b0a5a
2. See that the language is not changed to English/Polish properly in "Multiple popups" sample although I set it with:

```
language: elementId == 'ckfinder-input-2' ? 'pl' : 'en',
```

**Comment by zaak** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
