### ISSUE TITLE
Confusing demo message about uploading up to 10 files

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#102]
Message about uploading up to 10 files in the demo version is confusing. It suggests that one can upload 10 files. When user configures CKFinder to point to a folder with more than 10 files one cannot upload files at all.

**Comment by AnnaTomanek** [comment]
Fixed. The updated code will be publicly available in the upcoming release.

**Comment by Yannyezixin** [comment]
how i config it?
