### ISSUE TITLE
Scrollbar in maximized modal windows does not work correctly

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#109]
1. There is a scrollbar although there are just a few files in the files pane (because the parent page needs it).
2. The close button in the top-right corner is always cut off due to the scrollbar. 
3. If I have plenty of files in a folder and CKFinder maximized, the scrollbar on the right does not scroll files.

![screen shot 2015-05-04 at 14 14 31](https://cloud.githubusercontent.com/assets/545175/7453317/2ba276c0-f268-11e4-9a7b-098226919c18.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
