### ISSUE TITLE
CKFinder loads very slowly on IE11 in a popup

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#11]
It works terribly slow too.

**Comment by zaak** [comment]
Fixed. The updated code will be publicly available in the upcoming release.

**Comment by ralfbecker** [comment]
Can you tell what the problem was and how it was fixed?

We have a similar issue with popups referencing objects in the opener ...

**Comment by zaak** [comment]
@ralfbecker: The bug mentioned here was related to CKFinder popups internals, and was fixed it in CKFinder 3.0.0 release.

Could you please open a new issue and describe in details the issue you encountered?

**Comment by ralfbecker** [comment]
I'm not referring to a CKEditor problem, but experiencing something similar in our own software and just wondering how you were able to solve it in CKEditor/Finder.

Maybe you can point me to the commit which fixed it.

**Comment by zaak** [comment]
@ralfbecker: The JavaScript source code of CKFinder is not public, so I can't point you to the commit.

In short, some of the third party libraries we use had to be loaded in the scope of popup document, and not used from `opener` window, because that caused performance issues.
