### ISSUE TITLE
Dialogs: Leaking hotkeys

### ISSUE THREAD

**Issue by jodator** [ckfinder/ckfinder#116]
Seems that hotkeys from dialog leaks somehow to the application? TC:

1. Open full page sample.
1. Make sure that you have at least 2 files in files pane.
1. Select any file.
1. Use rename function.
1. Having a focus in the text input (default) press `ctrl+a`.

	**Expected**: Whole text in the input should be selected.
	
	**Actual**: All items in background become selected.

**Comment by fredck** [comment]
Just faced exactly this TC when playing with the demo... seems to be a common case so.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
