### ISSUE TITLE
Yellow border below a folder that is not focused

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#132]
Found on Firefox, full page sample.

Setup:
 - Files resource type has no subfolders
 - Images resource type has child folders.

![screen shot 2015-05-27 at 13 03 45](https://cloud.githubusercontent.com/assets/545175/7834597/0540aed2-0471-11e5-80df-ebe4dde4d553.png)

Expand the Images folder, result:

![screen shot 2015-05-27 at 13 03 59](https://cloud.githubusercontent.com/assets/545175/7834599/0be3c86e-0471-11e5-9a3f-f5c16f85c13a.png)

Problems:
 - bottom yellow border is missing,
 - yellow border below Images is shown.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
