### ISSUE TITLE
IE:Initial shif+Tab moves focus to nowhere while it should to search field.

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#134]
This is IE only issue. Reproducible IE9-11.

**Comment by jswiderski** [comment]
To reproduce: Load Widget sample (Focus is on one of folders in folder pane) and press Shift+Tab.

**Comment by jswiderski** [comment]
Actually Shift+Tab works only when focus is in search Field. Shift+Tab moves focus to toolabr. In other cases like Shift+Tab from focused image or from Folder don't work.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
