### ISSUE TITLE
IE: Tab from Settings button goes to link after CKF

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#138]
Put focus on Settings button:
![focus](https://cloud.githubusercontent.com/assets/5314687/7835126/98abc6b6-0476-11e5-8a6a-350b636eb9f6.png)
Press Tab - focus goes to link under CKFinder:
![focustab](https://cloud.githubusercontent.com/assets/5314687/7835144/c237ad1a-0476-11e5-92d6-99dedef65725.png)
__This doesn't have to be Settings button. In fact Tabbing from any button in toolbar moves focus to ....__

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
