### ISSUE TITLE
Focus from last folder goes to nowhere.

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#140]
Put focus into last folder by clicking it:
![focus](https://cloud.githubusercontent.com/assets/5314687/7835575/6104bf52-047a-11e5-871c-b671928c9bf8.png)
Press tab.

Result: Focus goes to nowhere instead to Files panel.

__If you press Shift+Tab to focus whole folder panel and then press tab focus goes to files panel (It won't work in IE).__

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
