### ISSUE TITLE
There are two focuses in CKFinder and they focus different elements.

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#141]
Reproducible in all browsers.

![focus](https://cloud.githubusercontent.com/assets/5314687/7835751/76762686-047b-11e5-86e5-94995ffd6dfa.png)

Click on images folder which has one XXX sub-folder. Next press down arrow.
Result is that blue focus is on images and yellow focus in on XXX what can be confusing for users.

__Please note that you can do the same with folders on same level.__  I'm writing this so that you don't give me "but this is parent and child folder so it makes perfect sense". It would if it happened only in that case.

**Comment by jodator** [comment]
> Result is that blue focus

It is not a focus indicator. The blue thing denotes selected/current folder.
