### ISSUE TITLE
There is no yellow indicator wen copying/moving files.

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#142]
Please see the image:
![copyfocus](https://cloud.githubusercontent.com/assets/5314687/7836623/c768d6e6-0481-11e5-99c9-81e81f46214a.png)

There is no yellow indicator abound Files folder.

**Comment by jodator** [comment]
Same as in #141. The yellow indicator is for focus only. Hover state is that blue background of folder.
