### ISSUE TITLE
There is no possibility to enter Resource Types in Compact View

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#145]
After entering the root folder "/" you can try tabbing around or pressing arrows but entering one of folders - I was able to do it from time to time accidentally.

![compactview](https://cloud.githubusercontent.com/assets/5314687/7837412/0ae9df96-0487-11e5-95dc-2bbe9540713e.png)

**Comment by wwalc** [comment]
Note: only resource types have this problem.

**Comment by jswiderski** [comment]
The same goes for Mobile View.
![focus3](https://cloud.githubusercontent.com/assets/5314687/7838468/5883fa7e-048d-11e5-8351-a5b600feb4e7.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
