### ISSUE TITLE
Enter/Space don't work on folders in Compact View

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#146]
Try focusing folder as shown below:
![folder1](https://cloud.githubusercontent.com/assets/5314687/7837696/f77e16d2-0488-11e5-8e76-4552c7cf0525.png)

![folder2](https://cloud.githubusercontent.com/assets/5314687/7837699/f98904a0-0488-11e5-995e-c6a0c2f0b7c7.png)

Pressing Enter or Space doesn't list folder files.

**Comment by jswiderski** [comment]
The same goes for Mobile View.
![focus3](https://cloud.githubusercontent.com/assets/5314687/7838468/5883fa7e-048d-11e5-8351-a5b600feb4e7.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
