### ISSUE TITLE
Enter key don't work on breadcrumbs

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#147]
Open CKFinder in compact mode. Focus breadcrumb, using arrow keys focus some folder, press enter.

Current result: nothing happens.
Expected result: folder is opened.

Found on Firefox, OSX.

**Comment by jswiderski** [comment]
Please also see: https://github.com/ckfinder/ckfinder/issues/145

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
