### ISSUE TITLE
Tabbing doesn't seem to work as expected in Compact View.

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#149]
![focus](https://cloud.githubusercontent.com/assets/5314687/7838302/63f517fe-048c-11e5-9253-fdf610c75f3b.png)
Focus Toolbar and start tabbing CKFinder. Focus goes to:
1. Toolabr
2. Folder Panel
3. Bottom Bar (IE only)
4. Whole CKFinder ????

The last two options don't seem to be necessary.

**Comment by jswiderski** [comment]
The same goes for Mobile View.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
