### ISSUE TITLE
Wrong focus on the first file if it was previously selected

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#163]
Found on Firefox.

1. Select the first file in the files pane.
2. Move focus to the folders panel.
3. Press tab + arrow key to move focus to the first file

Result: file is somehow focused (the yellow border is present), but the contextual toolbar is not updated. Also the blue background is missing.

https://vimeo.com/129085787

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
