### ISSUE TITLE
Change "Choose Scaled" to "Choose Resized"

### ISSUE THREAD

**Issue by AnnaTomanek** [ckfinder/ckfinder#164]
When read out of context "Choose Scaled" might be quite non-obvious. Not all languages use "scale" to mean "resize" (as Polish does), so this expression might be confusing. Moreover, if you have a look into a [dictionary](http://dictionary.reference.com/browse/scaled?s=t), the first few explanations for "scaled/scale" might not be what we are looking for.

I suggest we change it to "Choose Resized" (unless you have a better idea).

Note that this requires changes in the API, not just the language string.

**Comment by wwalc** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
