### ISSUE TITLE
kindly see the error below

### ISSUE THREAD

**Issue by christinewsy** [ckfinder/ckfinder#180]
![image](https://cloud.githubusercontent.com/assets/9941350/10188552/b92c5b1a-6792-11e5-9406-0487f8790925.png)

**Comment by wwalc** [comment]
One of the requirements for the PHP installation is the mentioned FileInfo extension: http://docs.cksource.com/ckfinder3-php/system_requirements.html 

It is disabled by default on some installations, for example on XAMPP. You need to enable it or contact server administrator to do this.
