### ISSUE TITLE
KCFinder always redirect to unknown page when click on any button

### ISSUE THREAD

**Issue by AmirAmirAmir** [ckfinder/ckfinder#182]
KCFinder is open smoothly but when click on Refresh it redirect to kcact:refresh,
when click on Upload redirect to kcact:upload and so on for settings, maximize, about.

**Comment by jodator** [comment]
Hi @AmirAmirAmir, you probably posted this in wrong repository as this is for [CKFinder](https://cksource.com/ckfinder) not KCFinder.
