### ISSUE TITLE
Toolbar buttons and context menu items should have name property

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#21]
Toolbar buttons should have machine names (code names) so that it was possible to filter them out using toolbar:reset events. Filtering using icon or label is ugly.

There have been requests in the past to be able to disable certain buttons like Help, View or Download.
Instead of adding configuration options for this, we should simply make it possible to be done using API.

Hm, actually this could apply to context menu items as well. In theory now this role is somehow taken by the group name, but if one wants to remove an item from a larger group, he can't do this.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
