### ISSUE TITLE
Option primaryPanelWidth doesn't seem to work correctly

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#27]
Set primaryPanelWidth:'400px'  and the result is (only top of the panel is expanded):

![panel](https://cloud.githubusercontent.com/assets/5314687/6981615/de9274f0-da04-11e4-9538-63ee27f1c5a8.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
