### ISSUE TITLE
RTL Mode: checkboxes in Settings are not RTL friendly

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#29]
Current situation:

![image](https://cloud.githubusercontent.com/assets/545175/6965811/6c578070-d954-11e4-83e5-2d99ece1661b.png)

Should be (but the labels should not be cut off):

![image](https://cloud.githubusercontent.com/assets/545175/6965935/5c686a0c-d955-11e4-86f8-1887d2d14d11.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
