### ISSUE TITLE
Missing carat-d icon - select element looks wrong 

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#3]
To reproduce, use the SettingsDemo plugin from [CKFinder sample plugins](https://github.com/ckfinder/ckfinder-docs-samples)

### jquery-mobile

![image](https://cloud.githubusercontent.com/assets/545175/7229410/a34710ba-e763-11e4-867f-06cd75ca9bc8.png)

There should be an icon on the right like here:

![image](https://cloud.githubusercontent.com/assets/545175/7229422/c84a86c6-e763-11e4-9a3c-4793eca2f6f2.png)

### moono

Same issue:

![image](https://cloud.githubusercontent.com/assets/545175/7229652/714d649e-e766-11e4-8afa-6cec2f5a4ea6.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
