### ISSUE TITLE
jQuery Mobile example throws errors

### ISSUE THREAD

**Issue by sebastiansulinski** [ckfinder/ckfinder#301]
I thought I let you know that your samples pages throw errors - example: [http://www.plugnstage.com/ckfinder/samples/skins-jquery-mobile.html](http://www.plugnstage.com/ckfinder/samples/skins-jquery-mobile.html)

**Comment by zaak** [comment]
Hi @sebastiansulinski. It seems like a broken installation. I have to ask you a few questions:

1. What's the version of CKFinder and how it was installed? Was it a zip package from our website?
2. Is `autoload_real.php` file indeed missing? Have you altered your installation any way? This file is present in our package, so it should be there.
3. Are file system permissions correct?

**Comment by sebastiansulinski** [comment]
Hi @zaak - that's actually ckfinder examples - not my website.

**Comment by sebastiansulinski** [comment]
Oh I see - weird, they seem to be using your branding etc. No worries then :)
