### ISSUE TITLE
forceAscii not working

### ISSUE THREAD

**Issue by mfive** [ckfinder/ckfinder#305]
Hi CKF Team,
our forceAscii is set to true. We use PHP and CK Finder 3.4.0 we have all needed extension active. CK Finder ist also working well. But files with names like "sen school, this.jpg" are not converted? Any clue? We have PHP Version 5.6.24-0+deb8u1

thank you

**Comment by zaak** [comment]
Hi @mfive. I'm sorry to say that, but this option doesn't work in current version of CKFinder.
Although, you can create a simple plugin that implements the required logic. Please have a look at documentation about [events](http://docs.cksource.com/ckfinder3-php/appstructure.html#before_command_events) and [plugins](http://docs.cksource.com/ckfinder3-php/plugins.html).

**Comment by mfive** [comment]
hi zaak. but class with former logic is still in the files? Local.php. But sure thanx i will check how to implement by myself. So you dont plan to implement in future versions? I thought many languages like german will still use this...

 **public function convertToFilesystemEncoding($fileName)**

**Comment by jmartigny** [comment]
@zaak Is it going to be fixed ? When ? We are paying full price for ckfinder enterprise edition and need this feature for keeping up with sane filenames for our >2000 customers SaaS solution. Can we please have an answer now that that it's been over a month that the question is asked ?

**Comment by jmartigny** [comment]
It's pretty annoying to have an option simply "not working in current version" for months when the option is in the default config file like anyother options.

**Comment by zaak** [comment]
@mfive, @jmartigny: This feature will be added in the next version of CKFinder that will be released within a few weeks.

**Comment by mfive** [comment]
ok fresh!

**Comment by zaak** [comment]
This issue has been fixed in CKFinder v3.4.2.
