### ISSUE TITLE
how to integrate Ckfinder with Amazon S3 storage

### ISSUE THREAD

**Issue by balajijana** [ckfinder/ckfinder#312]
Hi Support,

 I need to show the uploaded files from Amazon s3 storage  in the Ckfinder public files folder when i click on the Browse Server Button. Is there any possibility that i could integrate ckfinder and Amazon s3 storage and show the files from the Amazon s3 storage?

**Comment by zaak** [comment]
Hi @balajijana!

Yes, CKFinder supports Amazon S3 storage out of the box.

Here are links to connector docs:

**PHP**
http://docs.cksource.com/ckfinder3-php/configuration.html#configuration_options_backends_amazons3

**ASP.NET**
http://docs.cksource.com/ckfinder3-net/configuration.html#configuration_options_backends_amazon

**Comment by balajijana** [comment]
Hi Zaak,

  I need to use CKfinder for an angular 2 application. I need to get the files form the Amazon s3 storage and need to display it in the Ckfinder public folder when i click the browse button?. I am newbie. I have no idea how far it is suitable? can you please give me an idea?

**Comment by zaak** [comment]
@balajijana: Please start with our [Quick Start Gide](http://docs.cksource.com/ckfinder3/#!/guide/dev_installation) to run CKFinder samples. I think these will be very helpful at the beginning.

Note: CKFinder doesn't provide any kind of ready to use integration with Angular, but it's fairly simple to do that _manually_.

**Comment by balajijana** [comment]
Hi Do we have Ckfinder for javascript?

**Comment by zaak** [comment]
@balajijana: CKFinder consists of two parts:
- client-side application (written in JavaScript)
- server-side connector (for PHP or ASP.NET)

These two talk to each other and this is how CKFinder works. There's no way to make it work using only client-side JavaScript code.

**Comment by dagiac** [comment]
when will you support for S3 Java?
