### ISSUE TITLE
CkEditor with CkFinder for image upload in dinamyc architecture?

### ISSUE THREAD

**Issue by andrelimeira** [ckfinder/ckfinder#317]
I am not able to integrate CKEditor + CKFinder using CodeIgniter, with dynamic directories, as each user (email) accesses a different folder. I am currently using CKEditor 4 and CKFinder Trial Version 3.

Thanks, and I'm waiting, you currently have this resource type invalid error, but I'm passing Type = Images to CKFinder and it's still not recognizing it.

Cheers
![captura de tela 2017-03-13 as 09 56 28](https://cloud.githubusercontent.com/assets/698734/23855750/ba9f220e-07d5-11e7-942e-37ec8d1fbb39.png)

**Comment by zaak** [comment]
Hi @andrelimeira. It looks like a configuration issue. Could you please show your `config.php` file and the JavaScript code you use to setup CKFinder with CKEditor?
The param `Type` in the URL query looks invalid, it should be `type`.

**Comment by jswiderski** [comment]
I'm closing the ticket as we did not get any feedback from user.
