### ISSUE TITLE
RTL mode: settings panel jumps

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#33]
Found on Chrome.

When I open settings form it jumps to left and right and for a second I even have this (an empty space on the left side of the application):

![image](https://cloud.githubusercontent.com/assets/545175/6964696/d90a9968-d94b-11e4-8b51-b8ec7373bf61.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
