### ISSUE TITLE
upload file with 400 bad request error

### ISSUE THREAD

**Issue by 350050183** [ckfinder/ckfinder#332]
request payload seems not integrated.

------WebKitFormBoundaryRKZKpj7VyZDKDxCj
Content-Disposition: form-data; name="upload"; filename="dva.png"
Content-Type: image/png

------WebKitFormBoundaryRKZKpj7VyZDKDxCj--

**Comment by zaak** [comment]
Hi @350050183. Could you please provide more detailed information about this issue? Please have a look at [issue tracker instructions](https://docs-old.ckeditor.com/ckfinder3/#!/guide/dev_feedback).

**Comment by 350050183** [comment]
-On what browser (name, exact version) and operating system (name, exact version) did you find the bug?
Chrome  61.0.3163.100 on Mac OSX 10.13

-Are you able to reproduce it in other browsers?
YES.

-Which version of CKFinder are you using?
Latest download.

-Which server-side distribution of CKFinder are you using (e.g. PHP)?
PHP

-What are the operating system and server configuration where CKFinder is installed?
Nginx+PHP-FPM5.6

-Can the error be reproduced on any of the default samples provided with CKFinder or does it only occur when CKFinder is integrated with your application?
Did not try this.

-What are the exact steps to perform in order to reproduce the issue?
Click CKEditor IMG icon, click upload tab, select a png file, upload.

-If CKFinder shows any error message, please provide it.
{"error":{"number":109,"message":"无效请求。"}}

-Do you see any errors in the JavaScript console when the issue occurs? If yes, paste all details and/or provide a screenshot of the error console.
None.

-If CKFinder does not load, does the Network tab in your browser show any HTTP errors like 403/404?
None.


-In case of issues with file uploads, does the issue happen only when large files or files of certain type are uploaded?
Small file the same.


-If you think that screenshots may help in understanding the issue, please add some. Hint: In most browsers you can paste them directly from clipboard.
![image](https://user-images.githubusercontent.com/12798824/31811967-0f40fb88-b547-11e7-88aa-0cd44faee423.png)


-Does the error happen only with some particular setup? If yes, please explain.
None.

-More Information

Request URL:http://backend.domain.com/Public/Admin/vendors/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&CKEditor=brief&CKEditorFuncNum=1&langCode=zh-cn
Request Method:POST
Status Code:400 Bad Request
Remote Address:127.0.0.1:80
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cache-Control:no-cache
Connection:keep-alive
Content-Type:application/json
Date:Fri, 20 Oct 2017 08:05:05 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:nginx/1.8.0
Transfer-Encoding:chunked
X-Powered-By:PHP/5.6.30
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:2691
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryoQoejY8B0TnNVAAC
Cookie:PHPSESSID=1c443f59448d560924706268991b8b63; UM_distinctid=15c3946646c0-0589e8412b94b8-396b7807-fa000-15c3946646d543; qdid=-99999; CNSEInfo=RefId=10758821&tcbdkeyid=&SEFrom=&SEKeyWords=&RefUrl=; 17uCNRefId=10758821; __tctmc=250092292.89287134; __tctmd=250092292.737325; __tctmu=250092292.0.0; __tctmz=250092292.1496820810329.1.1.utmccn=(direct)|utmcsr=(direct)|utmcmd=(none); __tctma=250092292.1496820810216504.1496820810329.1496820810329.1496827985276.2; longKey=1496820810216504; __tctrack=0; cna=JU2pEdlRkkwCATr4DhSqz5MU; isg=ApmZtEtkJIcNE_gTwS-oY5YnqIOzjoy-qQ9Cm7tOEUA_wrlUA3adqAfSsLFO; Hm_lvt_1e6fd3a46a5046661159c6bf55aad1cf=1505375807; Hm_lpvt_1e6fd3a46a5046661159c6bf55aad1cf=1505718512; ckCsrfToken=W5RXgu5jnplrPDFTu66IG7GMHDlemobYB7Z5JX59
Host:backend.sanmaoyou.com
Origin:http://backend.sanmaoyou.com
Referer:http://backend.sanmaoyou.com/index.php/Admin/FmAudio/Index
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Query String Parameters
view source
view URL encoded
command:QuickUpload
type:Files
CKEditor:brief
CKEditorFuncNum:1
langCode:zh-cn
Request Payload
------WebKitFormBoundaryoQoejY8B0TnNVAAC
Content-Disposition: form-data; name="upload"; filename="add.png"
Content-Type: image/png


------WebKitFormBoundaryoQoejY8B0TnNVAAC--

**Comment by 350050183** [comment]
With latest ckeditor is OK
