### ISSUE TITLE
Can't connect to Amazon S3 - Authorization Mechanism not supported

### ISSUE THREAD

**Issue by sridhar85** [ckfinder/ckfinder#334]
Hi there, I downloaded ckfinder v3.4.1 and installed it on my system today. I am unable to get Amazon S3 working with it. At first, all I got was "unknown error" but when I set $config["debug"] to true, I was able to get an error posted to my error log:

`CKFinder.ERROR: Aws\S3\Exception\InvalidRequestException: AWS Error Code: InvalidRequest, Status Code: 400, AWS Request ID: XXXXXXXXXXXXXX, AWS Error Type: client, AWS Error Message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256., User-Agent: aws-sdk-php2/2.8.31 Guzzle/3.9.3 curl/7.47.0 PHP/7.1.5`

Here's my configuration:

> $config['privateDir'] = array(
>     'backend' => 'default',
>     'tags'   => '.ckfinder/tags',
>     'logs'   => '.ckfinder/logs',
>     'cache'  => '.ckfinder/cache',
>     'thumbs' => '.ckfinder/cache/thumbs',
> );

> $config['backends'][] = array(
> 	"name" => "default",
> 	"adapter" => "s3",
> 	"bucket" => "example-bucket",
> 	"region" => "us-east-2",
> 	"key" => "my-key",
> 	"secret" => "my-secret",
> 	"visibility" => "public",
> 	"baseUrl" => "https://s3.us-east-2.amazonaws.com/example-bucket/"
> );

I have not given you my bucket name or keys for security reasons. But rest assured that the bucket does in fact exist, it is located in us-east-2, and the credentials do have full read-write permissions for this bucket, which I've tested using the aws command line utility.

I'm using PHP 7.1.5 on nginx 1.13, and I'm running ckfinder standalone (I'm accessing it through https://www.mydomain.com/path/to/ckfinder/ckfinder.html).

Also, I have not bought a license yet as I want to make sure ckfinder works with our S3 bucket first.

Any idea how I can resolve this issue?

Thanks,
Sridhar

**Comment by zaak** [comment]
Hi @sridhar85. Thank you for a detailed issue description, it was really helpful! Looks like the version of CKFinder you are using is slightly outdated. Latest CKFinder version (v3.4.2) can be downloaded [here](https://ckeditor.com/ckeditor-4/download/#ckfinder). It contains a few important changes, like AWS SDK upgrade to version 3, so updating your CKFinder installation should resolve this issue.

**Comment by sridhar85** [comment]
@zaak Thanks for the quick response. I tried ckfinder 3.4.2 and it works fine with my Amazon S3 bucket. I think I mistakenly downloaded the older version because on the download page, the button that says "PHP Version" looks more like a selection/radio option and not a button. And there is only one button in the page that uses the word "Download". I must have been in a rush and didn't realize you are supposed to click on "PHP Version" and not use the select options and the "Download" button below.
