### ISSUE TITLE
CkFinder giving empty screen after browse from ckeditor 4

### ISSUE THREAD

**Issue by learn44** [ckfinder/ckfinder#348]
Hi  @zaak 
I integrated asp.net ckfinder v3.4.2 in my asp.net web application. It is giving empty screen and giving no error in console. I have checked throw all the paths for files they are correct. 
This is the html in inspect element which is generated:
<html class="ui-mobile" dir="ltr" lang="en"><head><base href="http://localhost:50804/dist/ckfinder/ckfinder.html?resourceType=Files&amp;CKEditor=form_0&amp;CKEditorFuncNum=0&amp;langCode=en">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
	<title>CKFinder 3 - File Browser</title>
<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="http://localhost:50804/dist/ckfinder/config.js" src="http://localhost:50804/dist/ckfinder/config.js"></script><link rel="stylesheet" href="http://localhost:50804/dist/ckfinder/libs/jquery.mobile.structure.css?ver=d5enx6"><link rel="stylesheet" href="http://localhost:50804/dist/ckfinder/skins/core/ckfinder.css?ver=d5enx6"><link rel="stylesheet" href="http://localhost:50804/dist/ckfinder/skins/moono/icons.css?ver=d5enx6"><link rel="stylesheet" href="http://localhost:50804/dist/ckfinder/skins/moono/ckfinder.css?ver=d5enx6"><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="http://localhost:50804/dist/ckfinder/libs/jquery.js?ver=d5enx6" src="http://localhost:50804/dist/ckfinder/libs/jquery.js?ver=d5enx6"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="http://localhost:50804/dist/ckfinder/libs/jquery.mobile.js?ver=d5enx6" src="http://localhost:50804/dist/ckfinder/libs/jquery.mobile.js?ver=d5enx6"></script></head>
<body class="ckf-feature-css-transition ckf-ui-mode-desktop ui-alt-icon" data-theme="a" role="application">

<script src="ckfinder.js"></script>
<script>
	CKFinder.start();
</script>

<div class="ckf-panel-scrollable ckf-panel-left ui-panel ui-panel-position-left ui-panel-display-push ui-panel-closed ui-body-a ui-panel-fixed" data-ckf-panel="folders" data-position="left" data-theme="a" aria-hidden="true" data-display="push"><div class="ui-panel-inner"><div class="ckf-panel-contents" style="height: 537px; overflow: auto;"><ul role="tree" data-role="listview" tabindex="20" class="ckf-tree" aria-label="Folders tree"></ul></div></div></div><div class="ckf-panel-scrollable ckf-panel-right ui-panel ui-panel-position-right ui-panel-display-overlay ui-panel-closed ui-body-a ui-panel-fixed ui-panel-animate" data-ckf-panel="settings" data-position="right" data-theme="a" aria-hidden="true" data-display="overlay"><div class="ui-panel-inner"><div role="banner" data-role="header" class="ckf-toolbar-items ui-header ui-bar-inherit"><button data-ckf-role="closePanel" data-icon="ckf-cancel" data-iconpos="notext" title="Close" class="ui-btn-left ui-btn ui-icon-ckf-cancel ui-btn-icon-notext ui-shadow ui-corner-all">Close</button></div><div class="ckf-panel-contents" style="height: 490px; overflow: auto;"><div></div></div></div></div><div class="ui-panel-dismiss"></div></body></html>

Further image is attahced:
![ckfinder](https://user-images.githubusercontent.com/36160863/36310226-2f2cf7f2-1349-11e8-983e-6c5647d0b978.PNG)

 These are the lines in ckeditor:
 filebrowserBrowseUrl: '../dist/ckfinder/ckfinder.html?resourceType=Files',
filebrowserUploadUrl: '../dist/ckfinder/connector?command=QuickUpload&type=Files',

Quick reply will appreciated.
Thanks

**Comment by zaak** [comment]
This issue was resolved through [technical support channel](https://ckeditor.com/contact/). Closing.
