### ISSUE TITLE
There is no focus when entering folder in 'no-tree' view

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#36]
I'm testing keyboard navigation in no-tree view.
I have /Files/test and test folder contains sub folders plus file.

I'm navigating with tab key, once I have focus on test folder, I hit enter and....

I think the focus should be placed on first file next to '..' but it is nowhere to be found.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
