### ISSUE TITLE
Brave Browser will not accept Javascript-CkEditor 5

### ISSUE THREAD

**Issue by diny13601** [ckfinder/ckfinder#387]
Brave Browser will not accept Javascript. So, I don't know of a way to install CkEditor 5. Is there a work around? Is there a way to revise CkEditor to allow me to use it? I would prefer to use Brave Browser for my safety.
Thank you

**Comment by zaak** [comment]
Hi @diny13601. To be able to use CKEditor you have to enable JavaScript, there is no other way. In Brave you can press the lion icon and click _enable scripts_.

I'm closing this issue as it is not related to CKFinder.
