### ISSUE TITLE
Custom back end connector documentation

### ISSUE THREAD

**Issue by diogoribeiro** [ckfinder/ckfinder#391]
Hi there,
I'm trying to find some documentation that could help me to build a custom connector for my application.

Unfortunately PHP and .Net aren't options for me, so I need to build my connector.

Is there any documentation to help with that?

**Comment by zaak** [comment]
Hi @diogoribeiro. Have a look at the list of [CKFinder commands](https://ckeditor.com/docs/ckfinder/ckfinder3-php/commands.html#commands_list) and their responses, it should help.

What programming language/stack will you use to build the connector?

**Comment by diogoribeiro** [comment]
Thanks @zaak.

I'm going to use golang for this connector. Do you know if someone has already built it?

**Comment by zaak** [comment]
@diogoribeiro No, I'm sorry but I don't know about any implementation in Golang. As for officially supported connectors we have PHP, .NET and Java joining soon.

**Comment by diogoribeiro** [comment]
That's okay.

Thanks for pointing me to the documentation, it'll be very helpful
