### ISSUE TITLE
Square radio buttons in the Moono skin

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#4]
To reproduce, use the SettingsDemo plugin from [CKFinder sample plugins](https://github.com/ckfinder/ckfinder-docs-samples)

![image](https://cloud.githubusercontent.com/assets/545175/7229358/0810486e-e763-11e4-973a-d1190085b66b.png)

jquery-mobile skin looks okay:

![image](https://cloud.githubusercontent.com/assets/545175/7229390/6228bf0c-e763-11e4-89b8-e43bc80d68e1.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
