### ISSUE TITLE
Reporting sensitive issues

### ISSUE THREAD

**Issue by zaak** [ckfinder/ckfinder#403]
@Geolabor Could you please contact us via https://ckeditor.com/contact/?

**Comment by Geolabor** [comment]
Based in last scan issue has been fixed. Thanks.

**Comment by zaak** [comment]
@Geolabor: Could you please clarify if there is any issue or not? Was it a false flag? Or you mean it's been fixed in the newer version of CKFinder?

In any case, please feel free to [contact us](https://ckeditor.com/contact/).
