### ISSUE TITLE
Not config language ja on ckfinder

### ISSUE THREAD

**Issue by loihuynh2017** [ckfinder/ckfinder#409]
Dear Admin.
I don't know param set on ckfinder and code on code:
With: http://prntscr.com/q2m4q4
+ command=Init
+ lang=ja
+ Type= Images
=> Images exp: http://prntscr.com/q2ly41

After check on code on file: ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Translator.php then get value $_GET['langCode'] then it error not get value set lang=ja.
Images exp: http://prntscr.com/q2lx3w
-------------------------------------------------------
Please help me check value get on code source.
Thank Admin

**Comment by vokiel** [comment]
To set a language of CKFinder instance you should use the `language` configuration option:

```javascript
var config = {};

// Load the Japanese interface.
config.language = 'ja';

CKFinder.popup( config );

```
https://ckeditor.com/docs/ckfinder/ckfinder3/#!/api/CKFinder.Config-cfg-language

**Comment by loihuynh2017** [comment]
Dear Vokiel
Current i'm confirm: https://ckeditor.com/docs/ckfinder/ckfinder3/#!/api/CKFinder.Config-cfg-language
File: config.js
var config = {};
// Load the Japanese interface.
config.language = 'ja';
CKFinder.popup( config );
 
File: config.php
$config['authentication'] = function () {
        return false;
    };

But show message is language english: "500": "The file browser is disabled for security reasons. Please contact your system administrator and check the CKFinder configuration file.",
core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\locales\en.json
=> With config lang is ja then show message language Japanese 

Please help me check value get on code source.
Thank Vokiel

**Comment by vokiel** [comment]
Could you please set auth to `true` and check if the UI will be translated?

```php
$config['authentication'] = function () {
    return true;
};
```

**Comment by loihuynh2017** [comment]
Dear Vokiel
This a request of function only user login then config  true else then false.
=> and use select upload images and debug -> see image: https://prnt.sc/q2ly41
 ->.../connect.php?command=Init&lang=ja&Type= Images.
But when check code on code source ckfinder [\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Translator.php] 
then 
public function __construct($langCode = null)
    {
        //$locale = $langCode ?: (isset($_GET['langCode']) ? (string) $_GET['langCode'] : 'en');

       // When change code:

       $locale = $langCode ?: (isset($_GET['lang']) ? (string) $_GET['lang'] : 'en');

     // => function that right

        $this->setLocale($locale);
    }

i'm change code: $_GET['langCode'] => $_GET['lang'].

Please help me check value get on code source.
Thank Vokiel

**Comment by vokiel** [comment]
The bug with not sending `langCode` from the frontend was already reported in our private bug tracker. It's fixed now and it will be available in the next release.

For now, you can change the code in the connector as you proposed:
```php
$locale = $langCode ?: (isset($_GET['lang']) ? (string) $_GET['lang'] : 'en');
```

**Comment by loihuynh2017** [comment]
Dear Vokiel
Thank you support,.
