### ISSUE TITLE
Make "Copy to" / "Move to" dialog windows more compact / less ugly

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#41]
Currently when using CKFinder in widget mode with 500px height the "conflict" dialog is cut off:

![image](https://cloud.githubusercontent.com/assets/545175/6898291/a0fe09a0-d6f9-11e4-9aa5-cb792cdda8e9.png)

The situation could be improved by better positioning of dialog windows, but by making the whole dialog smaller we'll make it better as well.

**What's wrong / What to improve:**

The title does not make sense ("Copy to"). If we change it to a more generic "Please confirm" we'd be able to reuse the same string in many places. What's more, "Please confirm" will be meaningful enough to make the "Confirm file action" message superfluous, thus possible to remove.

Note: the phrase "**Please confirm**" does not fit perfectly this particular case as the user does not confirm anything but is making a selection from multiple available choices. Any better suggestions are more than welcome. In any case, for the purpose of this ticket, let's assume that "Please confirm" is suitable enough.

![image](https://cloud.githubusercontent.com/assets/545175/6898544/18a6865c-d6fb-11e4-852d-9ee08face4da.png)

A sample place where "Please confirm" will fit better:

![image](https://cloud.githubusercontent.com/assets/545175/6898617/7ab94aaa-d6fb-11e4-8b0b-88ac3e0e90b5.png)

**Careful with mobiles:**

One important note though: on mobile devices the title of a dialog will not be displayed. Make sure on mobiles the dialog will make sense after making any changes.

![image](https://cloud.githubusercontent.com/assets/545175/6898560/39a2ba9c-d6fb-11e4-935e-8c6b3a608a60.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
