### ISSUE TITLE
Incorrect filebrowserUploadUrl generated by setupCKEditor function

### ISSUE THREAD

**Issue by Seb33300** [ckfinder/ckfinder#428]
When I use the `setupCKEditor` function to setup a CKEditor instance using CKFinder config, the `filebrowserUploadUrl` is not properly generated.

For example:
``` javascript
var config = {
    connectorPath: '/connector/path',
    connectorInfo: 'myCustomInfo=value',
    resourceType: 'MyCustomType'
};

CKFinder.config(config);
CKFinder.setupCKEditor(CKEDITOR.instances['instanceId']);
```

Using this code, the `filebrowserBrowseUrl` works properly.
=> When I click on the `Browse Server` button of the Image popup, I can see that the ajax requests contain proper `connectorInfo` and `resourceType` information:
```
/connector/path?command=GetFolders&lang=en&type=MyCustomType&currentFolder=%2F&hash=xxx&myCustomInfo=value
```

But the issue happens on the `filebrowserUploadUrl ` which seem to not be properly generated.
=> If I try to quick upload something (by pasting an image directly into the editor), this ajax request called is:
```
/connector/path?command=QuickUpload&type=Files&responseType=json
```
As you can see, `connectorInfo` and `resourceType` information are missing in the URL.
This issue also happen using the [`pass`](https://ckeditor.com/docs/ckfinder/ckfinder3/?mobile=/api/CKFinder.Config#cfg-pass) config option.

Because of this issue we are not able to use the quick upload on our project.
Unfortunately the code is obfuscated and not public so I cannot try to work on a fix for this issue.
But it should not be very hard to fix since it already works properly for `filebrowserBrowseUrl`

**Comment by zaak** [comment]
Hi @Seb33300. Parameters for `filebrowserBrowseUrl` are controlled by the third argument - please try calling `CKFinder.setupCKEditor()` the following way:

```js
var config = {
    connectorPath: '/connector/path',
    connectorInfo: 'myCustomInfo=value',
    resourceType: 'MyCustomType'
};

var uploadParameters = {
    type: 'MyCustomType',
    myCustomInfo: 'value'
};

CKFinder.config(config);
CKFinder.setupCKEditor(CKEDITOR.instances['instanceId'], config, uploadParameters);
```

**Comment by Seb33300** [comment]
Thank you!
