### ISSUE TITLE
Java 3.5.1 - client side code of ckfinder

### ISSUE THREAD

**Issue by mathewm3** [ckfinder/ckfinder#452]
Hi Team,

As part of readme provided along with [3.5.1 version](https://ckeditor.com/ckfinder/changelog/) of CKFinder of PHP and ASP , the client-side part is common for all 3 languages - ASP.NET, PHP and Java.

1. Client-side code is not available as part of [Java 3.5.1](https://download.cksource.com/CKFinder/CKFinder%20for%20Java/3.5.1/ckfinder_java_3.5.1.zip), can we use the client-side code available as part of ASP.net and PHP?
2. On file comparison, there is a difference between ckeditor.js available as part of [Asp.net 3.5.1](https://download.cksource.com/CKFinder/CKFinder%20for%20ASP.NET/3.5.1/ckfinder_aspnet_3.5.1.zip) and [PHP 3.5.1](https://download.cksource.com/CKFinder/CKFinder%20for%20PHP/3.5.1/ckfinder_php_3.5.1.zip). Which one is recommended for Java application with client side development

**Documentation**
CKFinder is made from two parts: the client side part and the server side connector(s).

_The client side part is common across all distributions_ (PHP and ASP.NET, Java in the future), while the server side parts are different for each language, that's why there are multiple documentation websites available.

**Comment by zaak** [comment]
Hi @mathewm3!

For convenience and easier setup, all the static assets of CKFinder 3 for Java are bundled in CKFinder's JAR archive. Thanks to this the static resources for the client side can be served by CKFinder's servlet (this is the default behavior which can be disabled with [`serveStaticResources`](https://ckeditor.com/docs/ckfinder/ckfinder3-java/latest/guides/configuration.html#servestaticresources) option).

If you would like to serve CKFinder's static assets on your own, you can simply unpack them from CKFinder's JAR archive:

1. `wget https://maven.cksource.com/com/cksource/ckfinder3/3.5.1/ckfinder3-3.5.1.jar`
2. `unzip ckfinder3-3.5.1.jar`
3. CKFinder's client side part can be found in `static/ckfinder` directory.

**Comment by mathewm3** [comment]
Thanks a lot, @zaak . I have been searching for this for almost a day. Did not find any link to get the JAR file.
