### ISSUE TITLE
Guide for CKFinder upgrade from 2.3 to 3.5.1

### ISSUE THREAD

**Issue by mathewm3** [ckfinder/ckfinder#456]
I am upgrading CKFinder from 2.3 to 3.5.1 and is facing a lot of issues since a majority of the functions are not available. Do we have any guide which will be helpful for the upgrade?

**Comment by vokiel** [comment]
Here you have the [Upgrading from CKFinder 2.x to 3.x](https://ckeditor.com/docs/ckfinder/ckfinder3/#!/guide/dev_upgrading) guide.

Keep in mind that CKFinder 3.x is a complete rewrite of the application.

**Comment by mathewm3** [comment]
Thanks for the quick response and let me know that is a complete re-write.

Sharing some more useful links which will be helpful for others:
https://ckeditor.com/docs/ckfinder/ckfinder3-php/upgrading.html
https://ckeditor.com/docs/ckfinder/ckfinder3/?mobile=/guide/dev_upgrading
https://stackoverflow.com/questions/31274595/ckfinder-3-upgrade-difficulty
https://ckeditor.com/docs/ckfinder/ckfinder3-php/upgrading.html#upgrading_2to3_embedding
https://ckeditor.com/docs/ckfinder/ckfinder3/#!/guide/dev_installation
https://ckeditor.com/docs/ckfinder/ckfinder3/#!/api/CKFinder.Config
