### ISSUE TITLE
The "Java connector" setup document is absolutely useless

### ISSUE THREAD

**Issue by robozb** [ckfinder/ckfinder#457]
https://ckeditor.com/docs/ckfinder/ckfinder3-java/latest/guides/quick-start.html

The servlet does nothing :(  com.cksource.ckfinder.servlet.CKFinderServlet

**Comment by robozb** [comment]
My test project: https://www.dropbox.com/sh/ffdxxjc6h06qsje/AACrwnHTH4lEkjWx8t-VbXQya?dl=0

**Comment by zaak** [comment]
Hi @robozb. It would be great if you could provide some details which part of this article is not clear enough.

If you would like to get help with integration, please feel free to contact our [dedicated support channel](https://ckeditor.com/contact).

**Comment by robozb** [comment]
Dear Zaak! Thank you so much!
