### ISSUE TITLE
CKFinder don't work in PHP ^8.0.3, getClass() is deprecated.

### ISSUE THREAD

**Issue by Freeeon** [ckfinder/ckfinder#477]
CKFinder don't work in PHP ^8.0.3, because getClass() is deprecated, json return `{"error":{"number":110,"message":"Unknown error."}}`. 

Bug located in CKSource/CKFinder/ArgumentResolver.php on line 65:
`if ($reflectionClass = $param->getClass()) {`

Resolving:
`if ($reflectionClass = new \ReflectionClass($param->getType()->getName())) {`

This solution works at PHP 8.0.8, Laravel 8.52 and ckfinder-laravel-package v3.5.2 

P.S: it's so sad that you don't have a public repository, I spent a few hours to find the bug, and I can't send PR to help others

**Comment by Kocal** [comment]
Hi,

This is just a deprecation, so the code should still works.

I think the real issue is that this piece of code is broken because `imagecreatefromstring` now returns a `GdImage` in PHP 8, so `is_resource()` does not work:
![image](https://user-images.githubusercontent.com/2103975/139429814-4706a2e5-e689-49dc-835f-9ea31f61fc58.png)

> P.S: it's so sad that you don't have a public repository, I spent a few hours to find the bug, and I can't send PR to help others

:+1:x10000

**Comment by Kocal** [comment]
For people using [composer patches](https://github.com/cweagans/composer-patches) and https://github.com/ckfinder/ckfinder-symfony-bundle, you can use the following patch:

```diff
--- a/vendor/ckfinder/ckfinder-symfony-bundle/Command/CKFinderDownloadCommand.php	2021-08-20 11:37:02.000000000 +0200
+++ b/vendor/ckfinder/ckfinder-symfony-bundle/Command/CKFinderDownloadCommand.php	2021-10-29 14:28:59.733497884 +0200
@@ -163,6 +163,18 @@
             $targetConnectorPath . '/README.md'
         ));

+        $output->writeln('Adding PHP 8 support');
+        $fs->dumpFile($filename = $targetConnectorPath.'/Image.php', str_replace(
+            '!is_resource($this->gdImage)',
+            '!is_resource($this->gdImage) && !$this->gdImage instanceof \GdImage',
+            file_get_contents($filename)
+        ));
+        $fs->dumpFile($filename = $targetConnectorPath.'/CommandResolver.php', str_replace(
+            '$reflectionClass = $param->getClass()',
+            '$reflectionClass = new \ReflectionClass($param->getType()->getName())',
+            file_get_contents($filename)
+        ));
+
         $output->writeln('<info>Done. Happy coding!</info>');
         return 0;
     }
```

It patches the `CKFinderDownloadCommand.php` file to apply PHP 8 patches after CKFinder connector has been downloaded and installed.

**Comment by Kocal** [comment]
Looks like this has been fixed..?

![image](https://user-images.githubusercontent.com/2103975/142613025-aec86b07-e53e-415f-a3ab-e6b1de79ec20.png)

**Comment by zaak** [comment]
@Kocal: That's correct. The issue has been fixed :+1:

**Comment by Kocal** [comment]
Thanks @zaak!
