### ISSUE TITLE
SubFolder arrow stays after removing folder

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#48]
Discovered in IE.

1. When in sub-folder e,g, Images->sub1
2. Create another sub-folder sub2
3. Click on sub2 and remove it.
Result: arrow in sub1 stays

Checkout the image below. The wwe is empty but the arrow is still there:
![arrow](https://cloud.githubusercontent.com/assets/5314687/6783124/6b48bb06-d178-11e4-80e9-157141cea316.png)

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
