### ISSUE TITLE
CKFinder 3.5.3 does not work on PHP <8.0.2

### ISSUE THREAD

**Issue by jamieburchell** [ckfinder/ckfinder#486]
I'm not sure if this was intentional, but the latest version does not only add PHP 8 / 8.1 support, but it also *requires* PHP 8.

When loading on PHP 7.4 an error message is shown from composer, stating that the environment conditions are incorrect and that PHP >= 8.0.2 is required due to the version constraints on some of the Symfony dependencies.

**Comment by zaak** [comment]
Hi @jamieburchell. That is correct, the newest version of CKFinder for PHP requires PHP 8.0+. If you would like to use CKFinder on PHP 7.4, please use version 3.5.2.

**Comment by jamieburchell** [comment]
@zaak You should mention this on the download page/README/change log. At the moment it reads like you've "added" PHP 8 support, because that's exactly what has been written.

You have also introduced breaking changes in a minor version bump, which IMO is extremely bad practice. I'm dealing with a lot of third party (open source, not paid commercial) projects at the moment who are readying for PHP 8/8.1 and so far all of them have managed to maintain compatibility with PHP 7.4+.
