### ISSUE TITLE
Maximize button in Full Page sample makes no sense

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#5]
![image](https://cloud.githubusercontent.com/assets/545175/7229313/94d8d460-e762-11e4-8a49-ef44e30ccead.png)

Ideally, CKFinder could automatically detect if this button makes sense. Perhaps simply if `CKFinder.start` is called, the Module could turn himself off?

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
