### ISSUE TITLE
how prevent ckfinder to doesn't add white background to uploaded image

### ISSUE THREAD

**Issue by hvaezapp** [ckfinder/ckfinder#503]
I upload an image with transparent background by ckfinder but ckfinder add white background to my image I don't want this 
how to prevent that?

**Comment by zaak** [comment]
@hvaezapp: Which version of CKFinder are you using? It would be helpful to understand more about your problem so we can reproduce the issue, but such information may be sensitive and doesn't need to be shared publicly. Could you please contact us through the [official support channel](https://ckeditor.com/contact/)?

**Comment by hvaezapp** [comment]
CKFinder version I use is version 2

**Comment by zaak** [comment]
@hvaezapp: CKFinder 2 is no longer supported, please consider upgrading to CKFinder 3.

**Comment by hvaezapp** [comment]
okay thanks for your response
