### ISSUE TITLE
Key navigation in Select Scaled dilaog is broken

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#51]
1. Open select Scaled dialog
2. By default Focus is on input field
3. Start Tabbing or Shift+Tabbing.
Result: once you reach one of "Small" or "Medium" or "Large" Buttons/Tabs and press any key (e.g. Tab or Arrow) **dialog is being 	closed**

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
