### ISSUE TITLE
Refresh folders on error 116

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#53]
When two people are using CKF at the same time, it may happen that one of them will delete some folder, then another will try to copy/move files to it.

In such case when Person 1 deletes a folder, Person 2 is not aware of it.
* Copy/Move - no errors is shown
* Click on deleted folder - no errors, just Loading screen

But we can see the error in the console:

```
error: {
  number: 116, 
  message: "Folder not found. Please refresh and try again."
}
```

We should refresh the folders list or at least show a proper message to the user.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
