### ISSUE TITLE
F5 / Refresh should also refresh the list of folders

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#54]
### Scenario 1
1. Open CKFinder in a popup in `Files:/Folder1`.
2. In a separate tab open CKFinder in `Files:/Folder1` and create `Files:/Folder1/Folder1.1`.
3. Hit F5 in a popup.
4. Result: `Folder 1.1` is not shown.

### Scenario 2
1. Open CKFinder in a popup in `Files:/`.
2. In a separate tab open CKFinder in `Files:/` and delete `Files:/Folder1`.
3. Hit F5 in a popup.
4. Result: `Folder 1.1` is still shown.

**Comment by wwalc** [comment]
Related: #53

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
