### ISSUE TITLE
Edit image: crop does not work correctly when the browser window is resized 

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#63]
1. Open CKFinder using e.g. 1920x1080 window.
2. Open Edit Image dialog and select crop operation. Create some small rectangle with selection, with some object that is easy to notice.
3. Resize the browser window to e.g. 1024x768. Move the rectangle above the same object. Note that the object "disappears", because the rectangle to show the crop selection shows the wrong portion of an image.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
