### ISSUE TITLE
CKFinder breaks when sizes of thumbnails are modified in config.php

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#65]
1. Open CKFinder in a browser, as a user set the size of thumbnails to 450
2. Open config.php and paste the following:

```
  'thumbnails' => array(
    'enabled'      => true,
    'sizes'        => array(
      array('width' => '150', 'height' => '150', 'quality' => 80),
      array('width' => '200', 'height' => '200', 'quality' => 80),
      array('width' => '250', 'height' => '250', 'quality' => 80),
    ),
    'bmpSupported' => true,
  ),
```

Note that the maximum allowed value is now smaller than the one that user set in his browser.

Result after refreshing the page - a JavaScript error, no toolbar and a completely empty files pane:
```
Uncaught TypeError: Cannot read property 'thumb' of undefined
```

![image](https://cloud.githubusercontent.com/assets/545175/5614639/4a519920-94f3-11e4-975c-a1069b21b5ef.png)

**Comment by zaak** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
