### ISSUE TITLE
Add some reasonable protection against caching issues

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#75]
People upgrade applications from time to time. The usually **don't** put them into a subfolder with a version number (e.g. `/ckfinder/3.0/`), which means that they are prone to various strange caching issues like:
 - Using an old, cached CSS file that does not suppot the new elements added by an updated JavaScript file (application).
 - Using an old, cached version of images (including sprite images, where the order has changed etc.).
 - Using mixed JavaScript files (an updated JS file with a new version of an application (`3.2`), while still requesting cached plugin files from the older version (`3.1`)).
 - ...and so on. 

Even if developers are aware of this and know how to clear the cache, the end users don't know this.

It looks like we should do two things:
 - Use Less to add unique timestamps during the build process (should be simple  http://www.bennadel.com/blog/2643-cache-busting-css-images-with-less-css.htm)
 - Use a function similar to http://docs.ckeditor.com/#!/api/CKEDITOR-method-getUrl in JavaScript

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
