### ISSUE TITLE
Lazy-load cloud resource types on Init

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#80]
In the future we should speed up the application startup time by making the Init command faster. 
Right now, using the default configuration file (where we have Dropbox enabled for one resource type), we have an ugly delay on startup just because of the slow Init command. 

"Slow" resource types should be flagged in the Init response so that CKFinder client side part knew that it should request their state after the application is ready. CKFinder could support a `lazy-load` property in the resource type configuration (in the server side configuration file) to make things simple and fully configurable.

**Comment by wwalc** [comment]
While working on this feature it turned out that we will speed up the application startup time for all resource types, not only cloud resources.

**Comment by zaak** [comment]
Done. The updated code will be publicly available in the upcoming release.
