### ISSUE TITLE
Upload stops working when Upload button is pressed at the wrong moment

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#86]
1. Click the Upload button, select a few files and upload them.
2. The upload bar should show up.
3. After the upload has finished, but before the upload bar closed himself, press the Upload button again. Do not select any files yet.
4. Wait a few seconds for the upload bar to close.
5. Select a couple of files from the system window and press "Ok/Open".
6. Result: the upload does not start.

**Comment by jodator** [comment]
Fixed. The updated code will be publicly available in the upcoming release.
